In [11]:
from sklearn.linear_model import LinearRegression
X=[[1],[2],[3],[4],[5],[6],[7]]
Y=[[1000],[1200],[1500],[1800],[5000],[7563],[6473]]
model=LinearRegression()
model.fit(X,Y)
prediction=model.predict([[7]])
print("Predicted Salary:",prediction[0])
print(model.coef_)
print(model.intercept_)

Predicted Salary: [7002.82142857]
[[1165.89285714]]
[-1158.42857143]

In [3]:
import pandas as pd
df=pd.read_csv("employee_data.csv")
print(df)

   employee_id             name   department   salary
0          101      Alice Smith  Engineering  85000.0
1          102        Bob Jones    Marketing  62000.0
2          103    Charlie Brown      Finance      0.0
3          104     Diana Prince          NaN  75000.0
4          105      Evan Wright  Engineering  92000.0
5          106  Fiona Gallagher           HR  58000.0
6          107     George Clark    Marketing      NaN
7          108    Hannah Abbott      Finance      0.0
8          109      Ian Malcolm        Sales  81000.0
9          110    Julia Roberts           HR  67000.0

In [4]:
print(df["name"].loc[:10],df["salary"].loc[0:10])

0        Alice Smith
1          Bob Jones
2      Charlie Brown
3       Diana Prince
4        Evan Wright
5    Fiona Gallagher
6       George Clark
7      Hannah Abbott
8        Ian Malcolm
9      Julia Roberts
Name: name, dtype: str 0    85000.0
1    62000.0
2        0.0
3    75000.0
4    92000.0
5    58000.0
6        NaN
7        0.0
8    81000.0
9    67000.0
Name: salary, dtype: float64

In [4]:
print(df["name"].iloc[:10],df["salary"].iloc[0:10])

0        Alice Smith
1          Bob Jones
2      Charlie Brown
3       Diana Prince
4        Evan Wright
5    Fiona Gallagher
6       George Clark
7      Hannah Abbott
8        Ian Malcolm
9      Julia Roberts
Name: name, dtype: str 0    85000.0
1    62000.0
2        0.0
3    75000.0
4    92000.0
5    58000.0
6        NaN
7        0.0
8    81000.0
9    67000.0
Name: salary, dtype: float64

In [8]:
df[["name","department"]][0:10]

              name   department
0      Alice Smith  Engineering
1        Bob Jones    Marketing
2    Charlie Brown      Finance
3     Diana Prince          NaN
4      Evan Wright  Engineering
5  Fiona Gallagher           HR
6     George Clark    Marketing
7    Hannah Abbott      Finance
8      Ian Malcolm        Sales
9    Julia Roberts           HR

In [10]:
df.iloc[0:10,[0,1]]

   employee_id             name
0          101      Alice Smith
1          102        Bob Jones
2          103    Charlie Brown
3          104     Diana Prince
4          105      Evan Wright
5          106  Fiona Gallagher
6          107     George Clark
7          108    Hannah Abbott
8          109      Ian Malcolm
9          110    Julia Roberts